const CartConstant = {
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  EDIT_ITEM_QUANTITY: "EDIT_ITEM_QUANTITY",
  ORDER_SUCCESS: "ORDER_SUCCESS",
  URL: "order"
};

export default CartConstant