const FilterSortConstant = {
  FILTER_NAME: "FILTER_NAME",
  FILTER_BY_PROPERTIES: "FILTER_BY_PROPERTIES",
  REMOVE_FILTER_SORT: "REMOVE_FILTER_SORT",
  ORDER_CHANGE: "ORDER_CHANGE"
};

export default FilterSortConstant;
