const ProductConstant = {
  FETCH_ALL: "FETCH_ALL",
  FETCH_BY_ID: "FETCH_BY_ID",
  FETCH_BY_ID_NOT_FOUND: "FETCH_BY_ID_NOT_FOUND",
  FETCH_BY_BRAND: "FETCH_BY_BRAND",
  FETCH_BY_MADEIN: "FETCH_BY_MADEIN",
  FETCH_BY_TYPE: "FETCH_BY_TYPE",
  ADD_NEW_SUCCESS: "ADD_NEW_SUCCESS",
  ADD_NEW_ERROR: "ADD_NEW_ERROR",
  EDIT_SUCCESS: "EDIT_SUCCESS",
  EDIT_ERROR: "EDIT_ERROR",
  DELETE: "DELETE",
  ADD_COMMENT: "ADD_COMMENT",
  URL: "products/"
};

export default ProductConstant