const ProductConstant = {
  FETCH_ALL: "FETCH_ALL",
  FETCH_BY_ID: "FETCH_BY_ID",
  FETCH_BY_ID_NOT_FOUND: "FETCH_BY_ID_NOT_FOUND",
  FETCH_BY_BRAND: "FETCH_BY_BRAND",
  FETCH_BY_MADEIN: "FETCH_BY_MADEIN",
  FETCH_BY_TYPE: "FETCH_BY_TYPE",
  URL: "products/"
};

export default ProductConstant